# Generated by Django 2.2 on 2019-04-12 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whichOne', '0002_auto_20190412_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(choices=[('lama', 'Where is the lama ?'), ('alpaga', 'Where is the alpaga ?')], default=1, max_length=200),
        ),
    ]
