# Generated by Django 2.2 on 2019-04-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whichOne', '0003_auto_20190412_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='alpagaIMG',
            field=models.ImageField(null=True, upload_to='static/alpaga', verbose_name='Alpaga image :'),
        ),
        migrations.AlterField(
            model_name='question',
            name='lamaIMG',
            field=models.ImageField(null=True, upload_to='static/lama', verbose_name='Lama image :'),
        ),
    ]
